# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ssm-parameter-store-policy-documents
  description: A Terraform module that generates JSON documents for access for common AWS SSM Parameter Store policies
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, ssm, parameter-store, iam, iam-policy, acl, chamber
